version: "3.9"

services:
  lms-main-db:
    image: postgres:latest
    container_name: lms-main-db-container
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgresql1995!
      POSTGRES_DB: LMSMain

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --verbose
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    depends_on:
      - keycloak-db
    restart: always

  user-service:
    build: ./LMSSystem
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      KEYCLOAK_CLIENT_ID: go-backend
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_REALM: master
      KEYCLOAK_URL: http://keycloak:8080
    depends_on:
      - keycloak
    restart: always

  main-service:
    build: ./MainService
    container_name: lms-main-app-container
    ports:
      - "8083:8083"
    environment:
      GORM_HOST: lms-main-db
      GORM_PORT: 5432
      GORM_USER: postgres
      GORM_PASSWORD: Postgresql1995!
      GORM_NAME: LMSMain
      USER_SERVICE_URL: http://user-service:8082
      KEYCLOAK_URL: http://keycloak:8080/realms/master
      KEYCLOAK_CLIENT_ID: go-backend
    depends_on:
      - keycloak
      - lms-main-db
      - user-service
    restart: always

  keycloak-setup-roles:
    image: postgres:latest
    container_name: keycloak-setup-roles
    depends_on:
      - keycloak
    volumes:
      - ./init-db/insert.sql:/insert.sql
    environment:
      - PGPASSWORD=keycloak
    entrypoint: >
      sh -c "
      echo 'Waiting for Postgres...' &&
      until pg_isready -h keycloak-db -U keycloak; do
        sleep 2;
      done;

      echo 'Waiting for realm master...' &&
      until psql -h keycloak-db -U keycloak -d keycloak -t -c \"SELECT 1 FROM realm WHERE name='master';\" | grep -q 1; do
        sleep 5;
      done;

      echo 'Waiting extra time for full init...' &&
      sleep 20;

      echo 'Executing insert.sql...' &&
      psql -h keycloak-db -U keycloak -d keycloak -f /insert.sql &&
      echo 'SUCCESS: Roles created!'
      "